version: "3.7"
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=cfabrica46
            - POSTGRES_PASSWORD=abcd
            - POSTGRES_DB=go_crud
        ports:
            - "5434:5432"
        volumes:
            - ./ias/init.sql:/docker-entrypoint-initdb.d/init.sql

    storage:
        build: .
        restart: always
        environment:
            - PORT=7070
            - DATABASE_HOST=postgres
            - DATABASE_PORT=5432
            - DATABASE_USER=cfabrica46
            - DATABASE_PASS=abcd
            - DATABASE_NAME=go_crud
        depends_on:
            - postgres
        ports:
            - "7070:7070"

networks:
    default:
        name: gokit-crud_network
        driver: bridge
